spring:
  application:
    name: eureka-provider
logging:
  level:
    root: INFO
#    org.springframework.web.servlet.DispatcherServlet: Debug
    org.springframework.cloud.sleuth: Debug
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

info:
  title: im a provider